### PR TITLE
buzzard, rxjs 5.5

### LINKED ISSUE #83: Cannot find module 'feathers' when using @feathersjs/client
### Steps to reproduce

(First please check that this issue is not already solved as [described
here](https://github.com/feathersjs/feathers/blob/master/.github/contributing.md#report-a-bug))

- [ ] Tell us what broke. The more detailed the better.
- [ ] If you can, please create a simple example that reproduces the issue and link to a gist, jsbin, repo, etc.

### Expected behavior
Tell us what should happen

### Actual behavior
Tell us what happens instead

### System configuration

Tell us about the applicable parts of your setup.

**Module versions** (especially the part that's not working):

**NodeJS version**:

**Operating System**:

**Browser Version**:

**React Native Version**:

**Module Loader**:

### PR DESCRIPTION
**Pull request by j2L4e**
Made everything ready for buzzard,
moved to rxjs 5.5 and pipeable operators

closes #83, #76, #77

### CODE REVIEW

File: src/resource.js [hunk 1]
```diff
@@ -22,29 +34,35 @@ module.exports = function (settings, method) {
...
-    const stream = source.concat(
-      source.exhaustMap(data => {
+    const stream = source.pipe(
+      concatMap(data => {
         // Filter only data with the same id
-        const filter = current => current[options.idField] === data[options.idField];
+        const filterFn = current => current[options.idField] === data[options.idField];
         // `removed` events get special treatment
-        const filteredRemoves = this.removed$.filter(filter);
+        const filteredRemoves$ = this.removed$.pipe(filter(filterFn));
```
Comment (daffl) [inline src/resource.js]: No deal breaker, personally I'm not a big fan of hungarian notation style flags (here the `$`) in variable names.

File: test/resource.test.js [hunk 2]
```diff
@@ -109,32 +126,53 @@ describe('reactive resources', () => {
...
+          text: 'A test message'
+        });
+        service.update(id, {
+          text: 'Updated',
+          prop: true
+        });
       }, done);
 
-      result.skip(1).first().subscribe(message => {
+      result.pipe(
```
[the remark this answers is not in the document]
Comment (j2L4e) [reply test/resource.test.js]: The old one is still there until rxjs 6.

The new one is pretty nice. You can pass in any function of type Observable => Observable, so composing your own operators is a piece of cake. Also there was the dependency problem with the prototype based operators. 
You can read up on it here https://github.com/ReactiveX/rxjs/blob/master/doc/pipeable-operators.md

File: src/resource.js [hunk 3]
```diff
@@ -22,29 +34,35 @@ module.exports = function (settings, method) {
...
+        );
+
+        return of(data).pipe(
+          concat(combinedEvents$)
         );
       }));
 
     // apply `let` function if set
-    const letStream = options.let ? stream.let(options.let) : stream;
+    const letStream = options.let ? stream.pipe(options.let) : stream;
```
Comment (j2L4e) [inline src/resource.js]: I think `options.let` should become `options.pipe` for consistency. Also it would encourage using the new style operators and this is major version anyway

File: src/resource.js (hunk 1 above)
Comment (j2L4e) [reply src/resource.js]: Yeah, sorry, I shouldn't mess with your naming conventions.
Observables are the only place where I use to do it, anyway. We can revert those.

File: src/resource.js (hunk 3 above)
Comment (daffl) [reply src/resource.js]: Done, I updated the PR.

**Comment by j2L4e** [comment]
There are quite a bunch of hungarians left, want me to get rid of those?

```
$ egrep -Ron '[a-zA-Z]+\$' src
src/index.js:56:created$
src/index.js:57:updated$
src/index.js:58:patched$
src/index.js:59:removed$
src/resource.js:42:removed$
src/resource.js:45:created$
src/resource.js:46:updated$
src/resource.js:47:patched$
src/strategies.js:14:source$
src/strategies.js:15:source$
src/strategies.js:18:source$
src/strategies.js:25:events$
src/strategies.js:26:created$
src/strategies.js:29:removed$
src/strategies.js:30:updated$
src/strategies.js:31:patched$
src/strategies.js:34:source$
src/strategies.js:36:events$
src/strategies.js:37:source$
src/strategies.js:42:source$
src/strategies.js:104:events$
src/strategies.js:105:created$
src/strategies.js:109:removed$
src/strategies.js:112:updated$
src/strategies.js:112:patched$
src/strategies.js:117:source$
src/strategies.js:121:events$
```

**Comment by daffl** [comment]
We can leave those for now since they are attached to the service object.
